-- Insert 44 English Grammar topic folders under "Ingiliz tili" subject
-- Category: mavzulashtirilgan, subject: Ingiliz tili

INSERT INTO public.test_folders (name, description, category, subject, price, duration_minutes, questions_count, is_active, difficulty)
VALUES
  ('Parts of Speech', 'Parts of Speech - Nouns, Pronouns, Verbs, Adjectives, Adverbs, Prepositions, Conjunctions, Interjections, Determiners', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Nouns', 'Singular and Plural, Countable/Uncountable, Collective, Possessive, Compound Nouns', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Articles', 'A/An, The, Zero Article', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Pronouns', 'Personal, Object, Possessive, Reflexive, Demonstrative, Indefinite, Relative, Interrogative Pronouns', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Adjectives', 'Types, Order, Comparative, Superlative Adjectives', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Adverbs', 'Manner, Time, Place, Frequency, Degree, Comparative Adverbs', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Present Tenses', 'Present Simple, Present Continuous, Present Perfect, Present Perfect Continuous', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Past Tenses', 'Past Simple, Past Continuous, Past Perfect, Past Perfect Continuous', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Future Tenses', 'Future Simple (Will), Be Going To, Future Continuous, Future Perfect, Future Perfect Continuous', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Modal Verbs', 'Can, Could, May, Might, Must, Have To, Should, Ought To, Need, Dare', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Question Forms', 'Yes/No Questions, Wh Questions, Subject Questions, Tag Questions, Indirect Questions', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Imperatives', 'Imperative sentences and commands', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('There Is / There Are', 'Existential clauses with there is/are', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Quantifiers', 'Some, Any, Much, Many, A Lot Of, Few/A Few, Little/A Little, Several, Plenty Of', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Gerunds and Infinitives', 'Gerunds, To Infinitive, Bare Infinitive, Verb Patterns', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Passive Voice', 'Present, Past, Future Passive, Passive with Modals, Advanced Passive Structures', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Reported Speech', 'Statements, Questions, Commands and Requests, Reporting Verbs', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Conditionals', 'Zero, First, Second, Third, Mixed Conditionals', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('Wishes and Regrets', 'Wish, If Only, Would Rather', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('Relative Clauses', 'Defining, Non-Defining Clauses, Relative Pronouns, Reduced Relative Clauses', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Clauses', 'Noun Clauses, Adjective Clauses, Adverb Clauses', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Prepositions', 'Time, Place, Movement Prepositions, Prepositional Phrases', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Conjunctions', 'Coordinating, Subordinating, Correlative Conjunctions', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Comparison', 'Comparatives, Superlatives, As...As, Less/Least', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Determiners', 'Articles, Demonstratives, Quantifiers, Possessives', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('Phrasal Verbs', 'Common phrasal verbs and their meanings', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('Idioms', 'Common English idioms and expressions', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('Collocations', 'Common word combinations in English', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('Word Formation', 'Prefixes, Suffixes, Compound Words', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Sentence Structure', 'Simple, Compound, Complex, Compound-Complex Sentences', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Inversion', 'Inverted sentence structures in English', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('Causative Forms', 'Have/Get something done and causative structures', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('Ellipsis and Substitution', 'Omission and replacement in English sentences', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('Emphasis Structures', 'Cleft sentences, fronting, and emphatic structures', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('Advanced Modal Structures', 'Advanced uses of modal verbs', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('Discourse Markers', 'Linking words and discourse markers in English', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('Advanced Grammar Review', 'Comprehensive review of advanced grammar topics', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('Mixed Grammar Tests', 'Mixed grammar exercises covering all topics', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('CEFR A1 Grammar', 'A1 level grammar topics and exercises', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('CEFR A2 Grammar', 'A2 level grammar topics and exercises', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'oson'),
  ('CEFR B1 Grammar', 'B1 level grammar topics and exercises', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('CEFR B2 Grammar', 'B2 level grammar topics and exercises', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'osrta'),
  ('CEFR C1 Grammar', 'C1 level grammar topics and exercises', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin'),
  ('CEFR C2 Grammar', 'C2 level grammar topics and exercises', 'mavzulashtirilgan', 'Ingiliz tili', 0, 30, 30, true, 'qiyin');
