INSERT INTO public.mock_tests (id, title, subject, type, price_cash, price_educoin, is_free, duration_minutes, questions_count) 
    VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 'Milliy Sertifikat Matematika (Full)', 'Matematika', 'milliy_sertifikat', 15000, 10, false, 180, 45)
    ON CONFLICT (id) DO NOTHING;

DELETE FROM public.mock_test_questions WHERE test_id = '4f88e25d-7521-4d37-885e-7a932b1f3c3a';
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 1, 'Savol 1 matni topilmadi.', 'multiple_choice', '{"options":["","","",""]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 2, '[2,2 ball]  Hisoblang :   7 ,   2 (1)   −   4 ,   4 (2) +  31  90', 'multiple_choice', '{"options":["3,1(3)","3,1(2)","2,1(3)","2,1(2)"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 3, '[2,2 ball]  Do‘kon 3 kunda jami 175 kg kartoshka sotdi. Agar ikkinchi kun uchinchi kunga nisbatan 1,5 marta ko‘p, birinchi kun esa ikkinchi kunga nisbatan 2,4 marta kam kartoshka sotgan bo‘lsa,   do‘kon birinchi kun necha kilogramm kartoshka sotgan?', 'multiple_choice', '{"options":["35","44","56","27"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 4, '[2,2 ball]  Xonaga eni hamda bo‘yi 2,4 m va 4 m bo‘lgan gilam to‘shalgan. Agar xonaning eni hamda bo‘yi 4 m va 6 m bo‘lsa,   xona yuzining necha foizini gilam egallagan?', 'multiple_choice', '{"options":["55","40","60","45  1\nMatematika fanidan namunaviy test topshiriqlari"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 5, '[1,3 ball]  Ifodaning qiymatini toping :  (√  4   −  √ 7 +  √  4 +   √ 7  ) 2', 'multiple_choice', '{"options":["7","14","11","22"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 6, '[1,3 ball]  Quyidagi sonlarni   o‘sish tartibida joylashtiring :  a   = 6 ,   b   = 4 √ 2 ,   c   = 2 √ 10', 'multiple_choice', '{"options":["a < b < c","c < b < a","b < a < c","c < a < b"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 7, '[2,2 ball]  Soddalashtiring :   ( √ 7 + 1   −  √ 3 ) ( √ 7 +   √ 3   −   1 )', 'multiple_choice', '{"options":["5 + 2 √ 3","3   −   2 √ 3","5   −   2 √ 3","3 + 2 √ 3"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 8, '[2,2 ball]  Agar   { a n }   arifmetik progressiyada   a 10   +   a 12   = 25   va   a 20   +   a 22   = 45   bo‘lsa,   a 11   +   a 21   ni toping.', 'multiple_choice', '{"options":["25","35","30","20  2\nMatematika fanidan namunaviy test topshiriqlari"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 9, '[2,2 ball]  Agar   { b n }   geometrik progressiyada   b 3   = 18   va   S 3   = 26   bo‘lsa,   b 1   ni toping.', 'multiple_choice', '{"options":["8 yoki 16","6 yoki 36","2 yoki 32","4 yoki 64"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 10, '[1,3 ball]  Agar   x   −   y   = 5   bo‘lsa,   6 x   + 5   −   6 y   ning qiymatini toping.', 'multiple_choice', '{"options":["35","25","30","40"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 11, '[2,2 ball]  Agar   n   =   − 3 ,   m   =   − 2   va   k   = 3   bo‘lsa,  (   4 n 2  m  ) 2  ·   k  m 2 n 2   :   k 3  ( mn ) 3   ·   mk 2  n 3   ning qiymatini toping.', 'multiple_choice', '{"options":["288","48","− 48","144"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 12, '[1,3 ball]  Soddalashtiring :   cos 3 α   + cos   α  sin 3 α   −   sin   α', 'multiple_choice', '{"options":["tg   α","ctg   α","2 ctg   α","2 tg   α  3\nMatematika fanidan namunaviy test topshiriqlari"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 13, '[2,2 ball]  2   ·  (  sin 4   π  8  + cos 4   3 π  8   + sin 4   5 π  8   + cos 4   7 π  8  )  ni   hisoblang .', 'multiple_choice', '{"options":["3,5","2","3","1"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 14, '[2,2 ball]  3 3 x   −   2   ·   3 2 x   + 9   ·   3 x − 2   = 0   tenglamaning   barcha haqiqiy ildizlari yig‘indisini (agar u bitta bo‘lsa, shu haqiqiy ildizni) toping.', 'multiple_choice', '{"options":["− 1","0,5","0","1"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 15, '[2,2 ball]  log 7   (3 x   + 5) +  √  log 2 7   (2 x   + 5) = 0   tenglama   nechta haqiqiy ildizga ega?', 'multiple_choice', '{"options":["3","1","0","2"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 16, '[1,3 ball]  2 x 2   −   5 x   −   3 = 0   tenglamaning ildizlari   x 1   va   x 2   bo‘lsa,   1  x 1  +  1  x 2  ni hisoblang.', 'multiple_choice', '{"options":["−   3  5","−   5  3","5  3","3  5  4\nMatematika fanidan namunaviy test topshiriqlari"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 17, '[2,2 ball]  x 2  3  +  48  x 2   = 10  (   x  3   −   4  x  )  tenglamaning   haqiqiy ildizlari yig‘indisini toping.', 'multiple_choice', '{"options":["10","6","− 1","4"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 18, '[1,3 ball]  √ x   + 18   <   2   −   x   tengsizlikni   yeching.', 'multiple_choice', '{"options":["( − 18;   − 1)","[ − 18;   − 2)","( − 18; 2)","[ − 18; + ∞ )"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 19, '[2,2 ball]  5 x   + 3  x 2   +   x   −   2   >   1   tengsizlikning   barcha butun yechimlari yig‘indisini toping.', 'multiple_choice', '{"options":["9","10","15","14"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 20, '[1,3 ball]  Quyidagi funksiyalardan   qaysi biri toq funksiya?', 'multiple_choice', '{"options":["y   =   x 4   +   ctgx","y   =   x 2  1 +   lgx","y   = sin   x   ·   ( 1 +   x 2 )","y   =   √ x   +   x 4  5\nMatematika fanidan namunaviy test topshiriqlari"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 21, '[2,2 ball]  Agar   f   ( x ) =   x 2   −   1   va   g   ( x ) = 3   −   2 x   bo‘lsa,   f   ( g   ( x ))   ni toping.', 'multiple_choice', '{"options":["4 x 2   −   12 x   + 8","4 x 2   + 12 x   −   8","5   −   2 x 2","4 x 2   −   6 x   + 8"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 22, '[2,2 ball]  f   ( t ) =   t 4   −   2 t 2   + 1   bo‘lsa,   f   ′   (1)   ni hisoblang.', 'multiple_choice', '{"options":["0","4","2","8"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 23, '[2,2 ball]  f   ( x ) =   1  1   −   cos( − x   + 8 π )   funksiyaning   boshlang‘ich funksiyasini toping.', 'multiple_choice', '{"options":["1  2  tg   x  2  +   C","−   1  2  ctg   x  2  +   C","−   ctg   x  2  +   C","−   tg   x  2  +   C"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 24, '[1,3 ball]  Ikki to‘g‘ri chiziqning kesishishidan hosil bo‘lgan qo‘shni burchaklarning ayirmasi   20 ◦   ga teng bo‘lsa,   bu burchaklardan kichigini toping.', 'multiple_choice', '{"options":["90 ◦","80 ◦","60 ◦","70 ◦  6\nMatematika fanidan namunaviy test topshiriqlari"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 25, '[1,3 ball]  ABC   teng yonli   ( AB   =   BC )   uchburchakning   BD   medianasi uzunligi 4 cm ga teng. Agar   ABD  uchburchak perimetri 12 cm ga teng bo‘lsa,   ABC   uchburchak perimetrini (cm) toping.', 'multiple_choice', '{"options":["9","8","16","18"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 26, '[2,2 ball]  Aylana   13 : 14 : 9   nisbatda uchta yoyga bo‘lingan va bo‘linish nuqtalari tutashtirilib uchburchak hosil qilingan. Agar hosil bo‘lgan uchburchakning kichik tomoni   4  √ 12   cm ga teng bo‘lsa,   aylanaga tashqi chizilgan muntazam uchburchakning yuzini (cm 2 ) toping.', 'multiple_choice', '{"options":["2   4  √ 3","9","36","3 √ 3"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 27, '[2,2 ball]  A D   C B F K x   x  3 y y  Chizmadagi   ABCD   parallelogrammning yuzi 64 cm 2   ga teng bo‘lsa,   F KCD   to‘rtburchakning yuzini (cm 2 ) toping.  Bunda   AF  F D   = 3 ,   AK  KB   = 1   ga teng.', 'multiple_choice', '{"options":["52","36","48","28  7\nMatematika fanidan namunaviy test topshiriqlari"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 28, '[2,2 ball]  Muntazam sakkizburchakka ichki va tashqi aylanalar chizilgan. Agar ichki chizilgan aylananing radiusi  r   = 2 +   √ 2   cm bo‘lsa,   bu aylanalar hosil qilgan halqaning yuzini (cm 2 ) toping.', 'multiple_choice', '{"options":["4 π","8 π","2 π","√ 2 π"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 29, '[2,2 ball]  α   tekislik va uni kesib o‘tmaydigan   AB   kesma berilgan.   AB   kesmaning uchlaridan   α   tekislikkacha bo‘lgan eng qisqa masofalar   AA 1   = 2   cm va   BB 1   = 7   cm ga teng.  A   uchidan boshlab hisoblaganda   AB   kesmani   3 : 2   nisbatda bo‘luvchi nuqtadan   α  tekislikkacha bo‘lgan eng qisqa masofani (cm) toping.', 'multiple_choice', '{"options":["5","3","4,5","4"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 30, '[2,2 ball]  Agar   | − → a   |   = 5   va  ∣ ∣ ∣ − →  b  ∣ ∣ ∣   = 4   ga teng bo‘lib, bu vektorlar orasidagi burchak   60 ◦   ga teng bo‘lsa,   5 − → a   −  − →  b  vektorning uzunligini toping.', 'multiple_choice', '{"options":["21","9","√ 41","√ 541"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 31, '[2,2 ball]  U   =   { x | −   10   ≤   x   ≤   10 , x   ∈   Z }   universal to‘plam hamda uning   A   =   { x | −   7   ≤   x   ≤   3 , x   ∈   Z }   va  B   =   { x | −   3   ≤   x   ≤   7 , x   ∈   Z }   qism to‘plamlari bo‘lsin.  ( A   ∪   B ) ′   to‘plamning elementlari sonini toping.   Bunda   ( A   ∪   B ) ′   to‘plam   A   ∪   B   to‘plamning to‘ldiruvchisi.', 'multiple_choice', '{"options":["2","6","8","4  8\nMatematika fanidan namunaviy test topshiriqlari"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 32, '[2,2 ball]  Qopchada har biri 8 tadan moviy va qizil sharlar bor.  Ketma-ket olingan ikki shardan ikkalasining ham moviy bo‘lish ehtimolligini toping.', 'multiple_choice', '{"options":["1  4","7  15","7  30","1  8  Topshiriqlar (33-35) va javob variant (A-F) larini o‘zaro moslashtiring.  Uzunligi 6 m va asosining radiusi 5 dm ga teng bo‘lgan silindrsimon shakldagi yog‘och bo‘lagidan eng katta hajmli to‘g‘ri burchakli parallelepiped shaklidagi yog‘och ustun yasaldi.  Bo‘yi Eni Yog‘och bo‘lagi"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 33, '[2,2 ball]  Yasalgan ustun asosining yuzini (dm 2 ) toping.', 'multiple_choice', '{"options":["Variant A","Variant B","Variant C","Variant D","Variant E","Variant F"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 34, '[2,2 ball]  Yasalgan ustunning hajmini (m 3 ) toping.', 'multiple_choice', '{"options":["Variant A","Variant B","Variant C","Variant D","Variant E","Variant F"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 35, '[2,2 ball]  Ustun   yasash   natijasida   (jarayonida)   yog‘och   bo‘lagining   necha   foizi chiqindiga chiqqan? ( π   ≈   3   deb oling)  A)   30  B)   3  C)   50  D)   25  E)   33  1  3  F)   3000  9
Matematika fanidan namunaviy test topshiriqlari', 'multiple_choice', '{"options":["Variant A","Variant B","Variant C","Variant D","Variant E","Variant F"]}', '"A"', null, null);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 36, 'Tenglamani yeching:   ( x   −   1) 4   + 2 x   =   x 2   + 73  [1,5 ball]  a) Tenglama nechta haqiqiy ildizga ega?  Javob : a)  [1,7 ball]  b) Tenglamaning haqiqiy ildizlari ko‘paytmasini toping.  Javob : b)  Diqqat!   Javoblaringizni javoblar varaqasiga ko‘chirib yozing.', 'written', '{"options":["","","",""]}', '{"a": "...", "b": "..."}', 1.5, 1.7);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 37, 'Tenglamani yeching:   sin 7 x   ·   cos   x   = sin 6 x  [1,5 ball]  a) Tenglamaning eng kichik musbat ildizini toping.  Javob : a)  [1,7 ball]  b) Tenglama   x   ∈   [ − π ;   π ]   kesmada nechta haqiqiy ildizga ega?  Javob : b)  Diqqat!   Javoblaringizni javoblar varaqasiga ko‘chirib yozing.', 'written', '{"options":["","","",""]}', '{"a": "...", "b": "..."}', 1.5, 1.7);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 38, 'Quyidagi chizmada   f   ( x ) =   ax 2   +   bx   + 6   funksiyaning grafigi tasvirlangan.   Parabola uchi   B  (   1  2  ; 6  1  4  )  nuqtada joylashgan bo‘lib,   f   ( x )   funksiya grafigi   Oy   o‘qini   A   nuqtada,   Ox   o‘qini esa abssissalari   x 1   va   x 2  ( x 1   < x 2 )   bo‘lgan nuqtalarda kesib o‘tgan.  x y B (   1  2   ; 6   1  4  )  A x 1   x 2  [1,5 ball]  a)   x 2  x 1  ni toping.  Javob : a)  [1,7 ball]  b)   A   va   B   nuqtalar orasidagi masofani toping.  Javob : b)  Diqqat!   Javoblaringizni javoblar varaqasiga ko‘chirib yozing. 10
Matematika fanidan namunaviy test topshiriqlari', 'written', '{"options":["","","",""]}', '{"a": "...", "b": "..."}', 1.5, 1.7);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 39, 'Quyidagi chizmada   ( − 6; 12)   oraliqda aniqlangan   y   =   f   ′   ( x )   funksiyaning grafigi tasvirlangan.   Bunda  y   =   f   ′   ( x )   funksiya   y   =   f   ( x )   funksiyaning hosilasi.  x y y   =   f   ′ ( x )  0 1 -6   12 -3 1 3 10 5   7  [1,5 ball]  a)   y   =   f   ( x )   funksiyaning   ( − 6; 12)   oraliqdagi lokal maksimum nuqtalari sonini toping.  Javob : a)  [1,7 ball]  b)   y   =   f   ( x )   funksiyaning   ( − 6; 12)   oraliqdagi lokal minimum nuqtalari sonini toping.  Javob : b)  Diqqat!   Javoblaringizni javoblar varaqasiga ko‘chirib yozing.', 'written', '{"options":["","","",""]}', '{"a": "...", "b": "..."}', 1.5, 1.7);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 40, 'Bizga   f   ( x ) = 2 √ x   va   g   ( x ) = 2 x   funksiyalar berilgan bo‘lsin.  [1,5 ball]  a)   f   ( x )   va   g   ( x )   funksiyalar nechta umumiy nuqtaga ega?  Javob : a)  [1,7 ball]  b)   f   ( x )   va   g   ( x )   funksiyalar grafiklari bilan chegaralangan shakl yuzini hisoblang.  Javob : b)  Diqqat!   Javoblaringizni javoblar varaqasiga ko‘chirib yozing. 11
Matematika fanidan namunaviy test topshiriqlari', 'written', '{"options":["","","",""]}', '{"a": "...", "b": "..."}', 1.5, 1.7);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 41, 'Quyidagi chizmada radiusi 1 cm ga teng va markazi   O   nuqtada bo‘lgan aylana tasvirlangan.   F   va   G  nuqtalar aylanaga tegishli bo‘lib,   O ,   F   va   E   nuqtalar bir to‘g‘ri chiziqda yotadi. Bunda   ∠ GEF   = 2 ◦   va  GE   = 1   cm.  O E F G  1 cm 1 cm 2 ◦  [1,5 ball]  a)   ∠ EGF   ni toping.  Javob : a)  [1,7 ball]  b)   ∠ EF G   ni toping.  Javob : b)  Diqqat!   Javoblaringizni javoblar varaqasiga ko‘chirib yozing. 12
Matematika fanidan namunaviy test topshiriqlari', 'written', '{"options":["","","",""]}', '{"a": "...", "b": "..."}', 1.5, 1.7);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 42, 'ABCD   kvadratning ichki sohasida chizmadagi kabi   KLGE   kvadrat joylashtirilgan.   Bunda   AE   = 6   cm va   ED   = 8   cm.  A C F B D G K  6 cm   8 cm E L  [1,5 ball]  a)   CG   kesma uzunligini (cm) toping.  Javob : a)  [1,7 ball]  b)   KLGE   kvadratning yuzini (cm 2 ) toping.  Javob : b)  Diqqat!   Javoblaringizni javoblar varaqasiga ko‘chirib yozing.', 'written', '{"options":["","","",""]}', '{"a": "...", "b": "..."}', 1.5, 1.7);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 43, 'Koordinatalar tekisligida markazi   M   nuqtada bo‘lgan aylana   Oy   o‘qiga   A   nuqtada,   Ox   o‘qiga esa  C   nuqtada urinadi (rasm). Koordinatalari (6;0) va (0;8) bo‘lgan nuqtalarni tutashtirishdan hosil bo‘lgan kesma aylanaga   B   nuqtada urinadi.  y O   x M   ( x ;   y )  A C  8 6  B  [1,5 ball]  a) Aylana radiusini toping.  Javob : a)  [1,7 ball]  b) Aylana markazidan koordinata boshigacha bo‘lgan masofani toping.  Javob : b)  Diqqat!   Javoblaringizni javoblar varaqasiga ko‘chirib yozing. 13
Matematika fanidan namunaviy test topshiriqlari', 'written', '{"options":["","","",""]}', '{"a": "...", "b": "..."}', 1.5, 1.7);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 44, 'Uchi   S   nuqtada bo‘lgan   SABC   muntazam uchburchakli piramida yon qirrasining uzunligi asosining tomonidan 2 marta katta.   SAB   uchburchakda   AH   balandlik va   ABC   uchburchakda   BM   mediana o‘tkazilgan.  [1,5 ball]  a)   AH   kesma uzunligining   BH   kesma uzunligiga nisbatini toping.  Javob : a)  [1,7 ball]  b)   M H   kesma uzunligining   BH   kesma uzunligiga nisbatini toping.  Javob : b)  Diqqat!   Javoblaringizni javoblar varaqasiga ko‘chirib yozing.', 'written', '{"options":["","","",""]}', '{"a": "...", "b": "..."}', 1.5, 1.7);
INSERT INTO public.mock_test_questions (test_id, question_number, question_text, type, metadata, correct_answer, points_a, points_b)
        VALUES ('4f88e25d-7521-4d37-885e-7a932b1f3c3a', 45, 'Shaharni elektr energiyasi bilan ta’minlash maqsadida ikki xil kabeldan foydalanilgan.   Daryo tubidan o‘tadigan   F J   uzunlikdagi kabelning har bir kilometri uchun 7500$ dan va qirg‘oq bo‘ylab (yer ostidan)  JL   masofaga tortilgan kabelning har bir kilometri uchun 6000$ dan pul to‘langan.   Bunda daryoning kengligi   F E =1 km,   EL =5 km va   EL ⊥ F E   bo‘lib,   eng kam pul ($) sarflab   F   nuqta(stansiya)dan  L   nuqta(shahar)ga kabel tortib borilgan.  Daryo GES Shahar  F J   L x  5 km 1 km Yer Yer  E  [1,5 ball]  a) Qirg‘oq bo‘ylab   JL   masofaga tortilgan kabel uchun qancha mablag‘ ($) sarflangan?  Javob : a)  [1,7 ball]  b) Daryo tubidan   F J   masofaga tortilgan kabel uchun qancha mablag‘ ($) sarflangan?  Javob : b)  Diqqat!   Javoblaringizni javoblar varaqasiga ko‘chirib yozing. 14', 'written', '{"options":["","","",""]}', '{"a": "...", "b": "..."}', 1.5, 1.7);
